"""followers

Revision ID: 476e2496fca8
Revises: 87024695270d
Create Date: 2021-12-21 13:18:42.021627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '476e2496fca8'
down_revision = '87024695270d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
